# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topics',
            new_name='topic',
        ),
    ]
